'use client';
import { useMemo, useState } from 'react';
import { Activity, BarChart3, BrainCircuit, GitBranch, LineChart, ShieldCheck, Sparkles, Target, X } from 'lucide-react';
import CampaignTools from './CampaignTools';
import StrategySimulator from './StrategySimulator';
import LLMSettings from './LLMSettings';

type Props = { state: any; initiatives: any[] };
const benchmarks = { roi: 35, adoption: 67, data: 80, satisfaction: 75 };

export default function AnalyticsHub({ state, initiatives }: Props) {
  const [open, setOpen] = useState(false);
  const [tab, setTab] = useState('live');
  const [sandbox, setSandbox] = useState(false);
  const history = useMemo(() => state.history || [], [state.history]);
  const previous = history.length > 1 ? history[history.length - 2].metrics : null;
  const trends = useMemo(() => history.map((h: any) => h.metrics?.roi ?? 0), [history]);
  const status = (value: number, benchmark: number) => value >= benchmark ? 'text-emerald' : 'text-gold';
  return <>
    <button aria-label="Open analytics" onClick={() => setOpen(true)} className="fixed bottom-5 right-5 z-30 flex items-center gap-2 rounded-xl border border-emerald bg-ink px-4 py-3 text-xs font-bold text-white shadow-xl"><Activity size={16} className="text-emerald" /> Analytics <span className="rounded bg-emerald px-2 py-0.5 text-ink">Q{state.q}/12</span></button>
    {open && <div className="fixed inset-0 z-40 bg-ink/35" onClick={() => setOpen(false)}><aside role="dialog" aria-label="Insights and analytics" onClick={e => e.stopPropagation()} className="absolute right-0 top-0 flex h-full w-full max-w-[480px] flex-col bg-ink text-white shadow-2xl">
      <header className="flex items-center justify-between border-b border-white/10 p-5"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-emerald">Always-on intelligence</p><h2 className="mt-1 text-xl font-bold">Insights & analytics</h2></div><button onClick={() => setOpen(false)} aria-label="Close analytics" className="rounded-lg p-2 text-white/50 hover:bg-white/10 hover:text-white"><X size={18} /></button></header>
      <nav className="grid grid-cols-4 border-b border-white/10">{[['live', 'Live'], ['trends', 'Trends'], ['diagnostics', 'Diagnostics'], ['learn', 'Learn']].map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`border-b-2 px-2 py-3 text-[10px] font-bold uppercase tracking-wider ${tab === id ? 'border-emerald text-emerald' : 'border-transparent text-white/45'}`}>{label}</button>)}</nav>
      <div className="flex-1 overflow-y-auto p-5">
        {tab === 'live' && <div className="space-y-5"><div className="grid grid-cols-2 gap-3">{[['ROI', state.roi, benchmarks.roi], ['Adoption', state.adoption, benchmarks.adoption], ['Data readiness', state.data, benchmarks.data], ['Employee trust', state.satisfaction, benchmarks.satisfaction]].map(([label, value, benchmark]) => <div key={label as string} className="rounded-xl border border-white/10 bg-white/5 p-4"><p className="text-[10px] uppercase tracking-wider text-white/45">{label as string}</p><p className={`mt-2 text-2xl font-bold ${status(value as number, benchmark as number)}`}>{(value as number).toFixed(label === 'ROI' ? 1 : 0)}%</p><div className="mt-3 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-emerald" style={{ width: `${Math.min(100, (value as number) / (benchmark as number) * 100)}%` }} /></div><p className="mt-2 text-[10px] text-white/40">Benchmark {benchmark}%</p></div>)}</div><div className="rounded-xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-2"><Target size={16} className="text-emerald" /><b>Traffic-light scorecard</b></div><div className="mt-4 space-y-3">{[['Risk exposure', state.risk, 20, 'risk'], ['Efficiency', state.efficiency, 55, 'efficiency'], ['AI literacy', state.literacy, 70, 'literacy'], ['Satisfaction', state.satisfaction, 75, 'satisfaction']].map(([label, value, benchmark, key]) => <div key={label as string} className="flex items-center justify-between text-sm"><span className="text-white/65">{label as string}</span><span className={`font-bold ${(label === 'Risk exposure' ? (value as number) < (benchmark as number) : (value as number) >= (benchmark as number)) ? 'text-emerald' : 'text-gold'}`}>{(value as number).toFixed(0)}% · {previous ? ((value as number) - (previous[key as string] ?? value) >= 0 ? 'up' : 'down') : 'live'}</span></div>)}</div></div><button onClick={() => setSandbox(true)} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald px-4 py-3 text-sm font-bold text-ink"><GitBranch size={16} /> Open Strategy Simulator</button></div>}
        {tab === 'trends' && <div className="space-y-5"><div className="rounded-xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-2"><LineChart size={16} className="text-emerald" /><b>ROI trend by quarter</b></div><div className="mt-5 flex h-32 items-end gap-2">{(trends.length ? trends : [state.roi]).map((v: number, i: number) => <div key={i} className="group flex flex-1 flex-col items-center gap-1"><div className="w-full rounded-t bg-emerald/80" style={{ height: `${Math.max(5, Math.min(100, v))}%` }} /><span className="text-[9px] text-white/40">Q{i + 1}</span></div>)}</div></div><div className="rounded-xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-2"><BarChart3 size={16} className="text-emerald" /><b>Current vs benchmark</b></div><div className="mt-4 space-y-3">{[['ROI', state.roi, 35], ['Adoption', state.adoption, 67], ['Data', state.data, 80], ['Risk resilience', 100 - state.risk, 80]].map(([label, value, benchmark]) => <div key={label as string}><div className="flex justify-between text-xs"><span className="text-white/60">{label as string}</span><span>{(value as number).toFixed(0)} / {benchmark as number}</span></div><div className="mt-1 h-2 rounded bg-white/10"><div className="h-full rounded bg-emerald" style={{ width: `${Math.min(100, (value as number) / (benchmark as number) * 100)}%` }} /></div></div>)}</div></div></div>}
        {tab === 'diagnostics' && <div className="space-y-5"><div className="rounded-xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-2"><ShieldCheck size={16} className="text-emerald" /><b>Risk / reward profile</b></div><p className="mt-5 text-sm text-white/65">You are taking <b className="text-white">{state.risk.toFixed(0)}%</b> risk for <b className="text-emerald">{state.roi.toFixed(1)}%</b> ROI.</p><p className="mt-2 text-3xl font-bold text-emerald">{(state.roi / Math.max(state.risk, 1)).toFixed(1)}x</p></div><div className="rounded-xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-2"><BrainCircuit size={16} className="text-emerald" /><b>Human Capital Index</b></div><p className="mt-3 text-4xl font-bold text-emerald">{(state.adoption * .35 + state.satisfaction * .25 + state.literacy * .25 + state.alloc.people * 4 * .15).toFixed(0)}<span className="text-sm text-white/45"> / 100</span></p><p className="mt-3 text-xs leading-5 text-white/55">People allocation currently sits at {state.alloc.people}%. The learning question is whether adoption can keep pace with ambition.</p></div></div>}
        {tab === 'learn' && <div className="space-y-5"><div className="rounded-xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-2"><Sparkles size={16} className="text-emerald" /><b>Learning progress</b></div><p className="mt-3 text-3xl font-bold">Q{state.q} <span className="text-sm font-normal text-white/45">of 12</span></p><p className="mt-2 text-sm leading-6 text-white/60">Your strategy is evolving through consequences. Keep testing the relationship between people investment and ROI.</p></div><div className="rounded-xl border border-white/10 bg-white/5 p-4"><b>Framework snapshot</b><div className="mt-4 space-y-2 text-sm text-white/60"><p>McKinsey scaling <span className="float-right text-emerald">{state.adoption.toFixed(0)}%</span></p><p>BCG people allocation <span className="float-right text-emerald">{state.alloc.people}%</span></p><p>PwC responsible AI <span className="float-right text-emerald">{((state.compliance + state.satisfaction + 100 - state.risk) / 3).toFixed(0)}</span></p><p>Accenture maturity <span className="float-right text-white">{state.q >= 10 ? 'Scaled' : state.q >= 7 ? 'Aligned' : 'Building'}</span></p></div></div><LLMSettings /></div>}
        <CampaignTools state={state} />
      </div>
    </aside></div>}
    {sandbox && <StrategySimulator state={state} initiatives={initiatives} onClose={() => setSandbox(false)} />}
  </>;
}
