export function exportText(state:any, format:'txt'|'md'|'csv'|'json') {
  const history=state.history||[];
  const framework={
    rewired:{strategy:Math.min(100,state.roi+state.data/2),talent:state.literacy,operatingModel:state.adoption,technology:state.efficiency,data:state.data,scaling:state.adoption},
    bcg1070:{people:state.alloc?.people||0,technology:(state.alloc?.infra||0)+(state.alloc?.data||0),process:(state.alloc?.mlops||0)+(state.alloc?.compliance||0)},
    rai:Math.round((state.compliance+state.satisfaction+Math.max(0,100-state.risk))/3),trust:Math.round((state.compliance+state.satisfaction)/2),maturity:state.q>=10?'Scaled':state.q>=7?'Aligned':state.q>=4?'Implemented':'Exploratory'
  };
  const data={exportedAt:new Date().toISOString(),scenario:'Project Factory 2030',quarter:state.q,score:state.score,metrics:{roi:state.roi,revenue:state.revenue,efficiency:state.efficiency,adoption:state.adoption,risk:state.risk,data:state.data,satisfaction:state.satisfaction,literacy:state.literacy},allocation:state.alloc,framework,history};
  if(format==='json')return JSON.stringify(data,null,2);
  if(format==='csv'){const rows=[['Quarter','ROI','Revenue uplift','Efficiency','Adoption','Risk exposure','Data readiness','People budget','Initiatives'],...history.map((h:any)=>[h.q,h.metrics?.roi??'',h.metrics?.revenue??'',h.metrics?.efficiency??'',h.metrics?.adoption??'',h.metrics?.risk??'',h.metrics?.data??'',state.alloc?.people??'',(h.chosen||[]).join('|')])];return rows.map((row:any[])=>row.map((cell:any)=>`"${String(cell).replaceAll('"','""')}"`).join(',')).join('\n');}
  const lines=[`AI INVESTMENT CHALLENGE — ${format==='md'?'FULL REPORT':'QUICK SUMMARY'}`,`Scenario: Project Factory 2030`,`Current quarter: ${state.q} of 12`,`Score: ${state.score}/100`,`ROI: ${state.roi.toFixed(1)}%`,`Adoption: ${state.adoption.toFixed(0)}%`,`Risk exposure: ${state.risk.toFixed(0)}%`,`Data readiness: ${state.data.toFixed(0)}%`,``,`Framework snapshot`,`- McKinsey Rewired scaling: ${framework.rewired.scaling.toFixed(0)}/100`,`- BCG people allocation: ${framework.bcg1070.people}% (10-20-70 learning signal)`,`- PwC Responsible AI score: ${framework.rai}/100`,`- Bain trust score: ${framework.trust}/100`,`- Accenture maturity: ${framework.maturity}`];if(format==='md')lines.push('','Quarter history',...history.map((h:any)=>`- Q${h.q}: ${(h.chosen||[]).join(', ')} — ROI ${h.metrics?.roi??'pending'}%`));return lines.join('\n');
}
export function downloadExport(state:any,format:'txt'|'md'|'csv'|'json'){const content=exportText(state,format);const ext=format==='txt'?'txt':format;const blob=new Blob([content],{type:format==='csv'?'text/csv':'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`ai-investment-campaign-q${state.q}.${ext}`;a.click();URL.revokeObjectURL(url)}
